language: c++
sudo: false

compiler:
    - clang
    - gcc

addons:
  apt:
    packages:
    - libncurses5-dev
    - libreadline-dev
    - openssl
    - libgnutls-dev
    - libexpat1-dev
    - zlib1g-dev
    - build-essential
    - automake
    - autoconf
    - autopoint
    - gperf

script:
    - ./bootstrap
    - ./configure --prefix=/usr
    - make release-check -j4
    - make INSTALL_ROOT=appdir install ; find appdir/
    
after_success:
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -appimage
  - find ./appdir -executable -type f -exec ldd {} \; | grep " => /usr" | cut -d " " -f 2-3 | sort | uniq
  - curl --upload-file ./LFTP*.AppImage https://transfer.sh/LFTP-git.$(git rev-parse --short HEAD)-x86_64.AppImage
